[tool.poetry]
name = "random-distributions"
version = "0.1.0"
description = ""
authors = ["Nikhil Anand <nikhilanand@granular.ag>"]

[tool.poetry.dependencies]
python = "^3.9"
seaborn = "^0.11.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
